# Generated by Django 5.2.17 on 2026-08-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField()),
                ('instructor', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=80)),
                ('level', models.CharField(choices=[('Beginner', 'Pemula'), ('Intermediate', 'Menengah'), ('Advanced', 'Lanjutan')], default='Beginner', max_length=20)),
                ('duration', models.CharField(default='4 minggu', max_length=40)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('image_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
